/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ateliedocetentacao.form;

import ateliedocetentacao.model.Dados;
import ateliedocetentacao.model.Produto;
import ateliedocetentacao.model.Utilidades;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class TelaIFormProdutos extends javax.swing.JInternalFrame {
    private Dados msDados;
    private int proAtual = 0;
    private boolean novo = false;
    private DefaultTableModel mTabela;

    public void setDados(Dados msDados) {
        this.msDados = msDados;
    }    
    public TelaIFormProdutos() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtICadIdProduto = new javax.swing.JTextField();
        txtICadProNome = new javax.swing.JTextField();
        txtICadProQuantidade = new javax.swing.JTextField();
        btnICadCons = new javax.swing.JButton();
        cmbICadProUnMedidal = new javax.swing.JComboBox<>();
        btnICadCriar = new javax.swing.JButton();
        btnICadAlterar = new javax.swing.JButton();
        btnICadExcluir = new javax.swing.JButton();
        btnRetornar = new javax.swing.JButton();
        btnProsseguir = new javax.swing.JButton();
        btnICadSalvar = new javax.swing.JButton();
        btnICadCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabela = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtICadProPreço = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setTitle("Produtos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("ID Produto :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Nome :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Quantidade :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("Unidade de Medida :");

        txtICadIdProduto.setEnabled(false);

        txtICadProNome.setEnabled(false);

        txtICadProQuantidade.setEnabled(false);

        btnICadCons.setText("Consultar");
        btnICadCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnICadConsActionPerformed(evt);
            }
        });

        cmbICadProUnMedidal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Quilograma (kg)", "Grama (g)", "Litro (l)", "Unidade (un.)", "Pacote", "Peça", "Litro (L)", "Mililitro (ml)", "Caixa", "Fardo" }));
        cmbICadProUnMedidal.setEnabled(false);

        btnICadCriar.setText("Criar");
        btnICadCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnICadCriarActionPerformed(evt);
            }
        });

        btnICadAlterar.setText("Alterar");
        btnICadAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnICadAlterarActionPerformed(evt);
            }
        });

        btnICadExcluir.setText("Excluir");
        btnICadExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnICadExcluirActionPerformed(evt);
            }
        });

        btnRetornar.setText("<");
        btnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornarActionPerformed(evt);
            }
        });

        btnProsseguir.setText(">");
        btnProsseguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsseguirActionPerformed(evt);
            }
        });

        btnICadSalvar.setText("Salvar");
        btnICadSalvar.setEnabled(false);
        btnICadSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnICadSalvarActionPerformed(evt);
            }
        });

        btnICadCancelar.setText("Cancelar");
        btnICadCancelar.setEnabled(false);
        btnICadCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnICadCancelarActionPerformed(evt);
            }
        });

        tblTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTabela);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 102));
        jLabel5.setText("Preço :");

        txtICadProPreço.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtICadProNome, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtICadProPreço, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmbICadProUnMedidal, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtICadProQuantidade, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(txtICadIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnRetornar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnICadCons)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnICadCriar)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnICadAlterar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnICadExcluir))
                                    .addComponent(btnProsseguir)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnICadSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnICadCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtICadIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtICadProNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtICadProQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbICadProUnMedidal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtICadProPreço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnICadSalvar)
                    .addComponent(btnICadCancelar))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProsseguir)
                    .addComponent(btnRetornar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnICadCons)
                    .addComponent(btnICadCriar)
                    .addComponent(btnICadAlterar)
                    .addComponent(btnICadExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnICadCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnICadCriarActionPerformed
        btnICadCriar.setEnabled(false);
        btnICadCons.setEnabled(false);
        btnICadAlterar.setEnabled(false);
        btnICadExcluir.setEnabled(false);
        btnICadSalvar.setEnabled(true);
        btnICadCancelar.setEnabled(true);
        cmbICadProUnMedidal.setEnabled(true);
        btnProsseguir.setEnabled(false);
        btnRetornar.setEnabled(false);
        //Caixa de texto
        txtICadIdProduto.setEnabled(true);
        txtICadProNome.setEnabled(true);
        txtICadProQuantidade.setEnabled(true);
        txtICadProPreço.setEnabled(true);

        //limpar caixas de texto
        txtICadIdProduto.setText("");
        txtICadProNome.setText("");
        txtICadProQuantidade.setText("");
        txtICadProPreço.setText("");
        cmbICadProUnMedidal.setSelectedIndex(0);
        novo = true;
        txtICadIdProduto.requestFocus();
    }//GEN-LAST:event_btnICadCriarActionPerformed

    private void btnICadSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnICadSalvarActionPerformed
        if (txtICadIdProduto.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Favor inserir um numero de ID");
            txtICadIdProduto.requestFocusInWindow();
            return;
        }
        if (cmbICadProUnMedidal.getSelectedIndex()== 0){
            JOptionPane.showMessageDialog(rootPane,"Favor selecione uma Unidade de Medida");
            cmbICadProUnMedidal.requestFocusInWindow();
            return;
        }
        if (txtICadProNome.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Favor inserir um Nome");
            txtICadProNome.requestFocusInWindow();
            return;
        }
        if (txtICadProQuantidade.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Favor inserir uma Quantidade");
            txtICadProQuantidade.requestFocusInWindow();
            return;
        }
        if (txtICadProPreço.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Favor inserir um Preço");
            txtICadProPreço.requestFocusInWindow();
            return;
        }
        if (!Utilidades.isNumeric(txtICadProPreço.getText())){
            JOptionPane.showMessageDialog(rootPane,"Favor inserir Somente Numeros");
            txtICadProPreço.requestFocusInWindow();
            return;
        }
        int preco = Integer.parseInt(txtICadProPreço.getText());
        if (preco <= 0){
            JOptionPane.showMessageDialog(rootPane,"Favor inserir um Valor Acima de 0");
            txtICadProPreço.requestFocusInWindow();
            return;
        }
        
        //freio zé

        int pos = msDados.posicaoProduto(txtICadIdProduto.getText());
        if(novo){
            if(pos!=-1){
                JOptionPane.showMessageDialog(rootPane,"Este Produto Ja Existe");
                txtICadIdProduto.requestFocusInWindow();
                return;
            }
            }else{
                if(pos == -1){
                    JOptionPane.showMessageDialog(rootPane,"Este Produto Ainda Não Existe");
                    txtICadIdProduto.requestFocusInWindow();
                    return;
                }
            }
        
        
        Produto mProduto = new Produto(txtICadIdProduto.getText(),
                txtICadProNome.getText(),
                Integer.parseInt(txtICadProQuantidade.getText()), 
                preco, 
                cmbICadProUnMedidal.getSelectedIndex());
                                 
        String msg;
        if(novo){
            msg = msDados.adicionarProduto(mProduto);
        }else{
            msg = msDados.editarProduto(mProduto, pos);
        }
        JOptionPane.showMessageDialog(rootPane, msg);
        
        btnICadCriar.setEnabled(true);
        btnICadCons.setEnabled(true);
        btnICadAlterar.setEnabled(true);
        btnICadExcluir.setEnabled(true);
        btnICadSalvar.setEnabled(false);
        btnICadCancelar.setEnabled(false);
        cmbICadProUnMedidal.setEnabled(false);
        btnProsseguir.setEnabled(true);
        btnRetornar.setEnabled(true);
        //Caixa de texto
        
        txtICadIdProduto.setEnabled(true);
        txtICadProNome.setEnabled(true);
        txtICadProQuantidade.setEnabled(true);
        cmbICadProUnMedidal.setEnabled(true);
        txtICadProPreço.setEnabled(true);
        
        
        preencherTabela();
    }//GEN-LAST:event_btnICadSalvarActionPerformed

    private void btnICadCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnICadCancelarActionPerformed
        btnICadCriar.setEnabled(true);
        btnICadCons.setEnabled(true);
        btnICadAlterar.setEnabled(true);
        btnICadExcluir.setEnabled(true);
        btnICadSalvar.setEnabled(false);
        btnICadCancelar.setEnabled(false);
        cmbICadProUnMedidal.setEnabled(false);
        btnProsseguir.setEnabled(true);
        btnRetornar.setEnabled(true);
        //Caixa de texto
        txtICadIdProduto.setEnabled(false);
        txtICadProNome.setEnabled(false);
        txtICadProQuantidade.setEnabled(false);
        cmbICadProUnMedidal.setEnabled(false);
        txtICadProPreço.setEnabled(false);
        //limpar caixas de texto
        txtICadIdProduto.setText("");
        txtICadProNome.setText("");
        txtICadProQuantidade.setText("");
        cmbICadProUnMedidal.setSelectedIndex(0);
        txtICadProPreço.setText("");
        
    }//GEN-LAST:event_btnICadCancelarActionPerformed

    private void btnICadAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnICadAlterarActionPerformed
        btnICadCriar.setEnabled(false);
        btnICadSalvar.setEnabled(true);
        btnICadCancelar.setEnabled(true);
        btnICadCons.setEnabled(false);
        btnICadAlterar.setEnabled(false);
        btnICadExcluir.setEnabled(false);
        cmbICadProUnMedidal.setEnabled(true);
        btnProsseguir.setEnabled(false);
        btnRetornar.setEnabled(false);
        //Caixa de texto
        txtICadProNome.setEnabled(true);
        txtICadProQuantidade.setEnabled(true);
        cmbICadProUnMedidal.setEnabled(true);
        txtICadProPreço.setEnabled(true);
        
        novo = false;
        
        txtICadProNome.requestFocus();
    }//GEN-LAST:event_btnICadAlterarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        mostrarRegistro();
        preencherTabela();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarActionPerformed
        proAtual--;
        if (proAtual == -1){
            proAtual = msDados.numeroProdutos();
        }
        mostrarRegistro();
    }//GEN-LAST:event_btnRetornarActionPerformed

    private void btnProsseguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsseguirActionPerformed
        proAtual++;
        if (proAtual == msDados.numeroProdutos()){
            proAtual = 0;
        }
        mostrarRegistro();
    }//GEN-LAST:event_btnProsseguirActionPerformed

    private void btnICadExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnICadExcluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja deletar o cadastro?");
        if(resposta !=0){
            return;            
        }
        String msg;
        msg = msDados.deletarProduto(proAtual);
        JOptionPane.showMessageDialog(rootPane, msg);
        proAtual=0;
        mostrarRegistro();
        preencherTabela();
    }//GEN-LAST:event_btnICadExcluirActionPerformed

    private void btnICadConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnICadConsActionPerformed
        String produto = JOptionPane.showInputDialog("Favor Inserir Codigo do Produto");
        if(produto.equals("")){
            return;
        }
        int pos = msDados.posicaoProduto(produto);
        if(pos == -1){
            JOptionPane.showMessageDialog(rootPane,"Este Usuario Não Existe");
            return;
        }
        proAtual = pos;
        mostrarRegistro();
        
    }//GEN-LAST:event_btnICadConsActionPerformed

    private void mostrarRegistro(){
        txtICadIdProduto.setText(msDados.getProdutos()[proAtual].getIdproduto());
        txtICadProNome.setText(msDados.getProdutos()[proAtual].getNome());
        txtICadProQuantidade.setText("" + msDados.getProdutos()[proAtual].getQuantidade());
        cmbICadProUnMedidal.setSelectedIndex(msDados.getProdutos()[proAtual].getUn_medida());
        txtICadProPreço.setText("" + msDados.getProdutos()[proAtual].getPreco());
        
        
    }
    
    private void preencherTabela() {
        String titulos[] = {"ID Produto","Nome","Quantidade","Un.Medida","Preço"};
        String registro[] = new String[5];
        mTabela = new DefaultTableModel(null,titulos);
        for(int i = 0; i < msDados.numeroProdutos(); i++){
            registro[0]= msDados.getProdutos()[i].getIdproduto();
            registro[1]= msDados.getProdutos()[i].getNome();
            registro[2]= "" + msDados.getProdutos()[i].getQuantidade();
            registro[3]=  unmedida(msDados.getProdutos()[i].getUn_medida());
            registro[4]= "" + msDados.getProdutos()[i].getPreco();
            mTabela.addRow(registro);
        }
        tblTabela.setModel(mTabela);
    }
    
    private String unmedida(int idUNMEDIDA){
        switch(idUNMEDIDA){
            case 0: return"Quilograma (kg)";
            case 1: return"Grama (g)";
            case 2: return"Litro (l)";
            case 3: return"Unidade (un.)";
            case 4: return"Pacote";
            case 5: return"Peça";
            case 6: return"Litro (L)";
            case 7: return"Mililitro (ml)";
            case 8: return"Caixa";
            case 9: return"Fardo";
            default: return"NÃO DEFINIDO";
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnICadAlterar;
    private javax.swing.JButton btnICadCancelar;
    private javax.swing.JButton btnICadCons;
    private javax.swing.JButton btnICadCriar;
    private javax.swing.JButton btnICadExcluir;
    private javax.swing.JButton btnICadSalvar;
    private javax.swing.JButton btnProsseguir;
    private javax.swing.JButton btnRetornar;
    private javax.swing.JComboBox<String> cmbICadProUnMedidal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTabela;
    private javax.swing.JTextField txtICadIdProduto;
    private javax.swing.JTextField txtICadProNome;
    private javax.swing.JTextField txtICadProPreço;
    private javax.swing.JTextField txtICadProQuantidade;
    // End of variables declaration//GEN-END:variables
}
