/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ateliedocetentacao.form;

import ateliedocetentacao.model.Dados;
import ateliedocetentacao.model.Usuario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class TelaIFormUsuarios extends javax.swing.JInternalFrame {
    private Dados msDados;
    private int usuAtual = 0;
    private boolean novo = false;
    private DefaultTableModel mTabela;

    public void setDados(Dados msDados) {
        this.msDados = msDados;
    }    
    public TelaIFormUsuarios() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtICadIdUsuario = new javax.swing.JTextField();
        txtICadNome = new javax.swing.JTextField();
        txtICadEmail = new javax.swing.JTextField();
        txtICadUsername = new javax.swing.JTextField();
        btnICadCons = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cmbICadPerfil = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnICadCriar = new javax.swing.JButton();
        btnICadAlterar = new javax.swing.JButton();
        btnICadExcluir = new javax.swing.JButton();
        txtICadSenha = new javax.swing.JPasswordField();
        txtICadConfSenha = new javax.swing.JPasswordField();
        btnRetornar = new javax.swing.JButton();
        btnProsseguir = new javax.swing.JButton();
        btnICadSalvar = new javax.swing.JButton();
        btnICadCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabela = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setTitle("Usuarios");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("ID Usuario :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Nome :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Email :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("Nome de Usuario :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 102));
        jLabel5.setText("Senha:");

        txtICadIdUsuario.setEnabled(false);

        txtICadNome.setEnabled(false);

        txtICadEmail.setEnabled(false);

        txtICadUsername.setEnabled(false);

        btnICadCons.setText("Consultar");
        btnICadCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnICadConsActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("Perfil :");

        cmbICadPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Administrador", "Funcionario" }));
        cmbICadPerfil.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("Confirmar Senha:");

        btnICadCriar.setText("Criar");
        btnICadCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnICadCriarActionPerformed(evt);
            }
        });

        btnICadAlterar.setText("Alterar");
        btnICadAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnICadAlterarActionPerformed(evt);
            }
        });

        btnICadExcluir.setText("Excluir");
        btnICadExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnICadExcluirActionPerformed(evt);
            }
        });

        txtICadSenha.setEnabled(false);

        txtICadConfSenha.setEnabled(false);

        btnRetornar.setText("<");
        btnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornarActionPerformed(evt);
            }
        });

        btnProsseguir.setText(">");
        btnProsseguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsseguirActionPerformed(evt);
            }
        });

        btnICadSalvar.setText("Salvar");
        btnICadSalvar.setEnabled(false);
        btnICadSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnICadSalvarActionPerformed(evt);
            }
        });

        btnICadCancelar.setText("Cancelar");
        btnICadCancelar.setEnabled(false);
        btnICadCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnICadCancelarActionPerformed(evt);
            }
        });

        tblTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtICadConfSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(txtICadSenha))
                .addGap(26, 26, 26)
                .addComponent(btnICadSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnICadCancelar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtICadIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(cmbICadPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtICadNome, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtICadEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtICadUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRetornar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnICadCons)
                                .addGap(18, 18, 18)
                                .addComponent(btnICadCriar)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnICadAlterar)
                                .addGap(18, 18, 18)
                                .addComponent(btnICadExcluir))
                            .addComponent(btnProsseguir)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtICadIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cmbICadPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtICadNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtICadEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtICadUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtICadSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtICadConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnICadSalvar)
                    .addComponent(btnICadCancelar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProsseguir)
                    .addComponent(btnRetornar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnICadCons)
                    .addComponent(btnICadCriar)
                    .addComponent(btnICadAlterar)
                    .addComponent(btnICadExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnICadCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnICadCriarActionPerformed
        btnICadCriar.setEnabled(false);
        btnICadCons.setEnabled(false);
        btnICadAlterar.setEnabled(false);
        btnICadExcluir.setEnabled(false);
        btnICadSalvar.setEnabled(true);
        btnICadCancelar.setEnabled(true);
        cmbICadPerfil.setEnabled(true);
        btnProsseguir.setEnabled(false);
        btnRetornar.setEnabled(false);
        //Caixa de texto
        txtICadIdUsuario.setEnabled(true);
        txtICadNome.setEnabled(true);
        txtICadEmail.setEnabled(true);
        txtICadUsername.setEnabled(true);
        txtICadSenha.setEnabled(true);
        txtICadConfSenha.setEnabled(true);
        //limpar caixas de texto
        txtICadIdUsuario.setText("");
        txtICadNome.setText("");
        txtICadEmail.setText("");
        txtICadUsername.setText("");
        txtICadSenha.setText("");
        txtICadConfSenha.setText("");
        cmbICadPerfil.setSelectedIndex(0);
        novo = true;
        txtICadIdUsuario.requestFocus();
    }//GEN-LAST:event_btnICadCriarActionPerformed

    private void btnICadSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnICadSalvarActionPerformed
        if (txtICadIdUsuario.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Favor inserir um numero de ID");
            txtICadIdUsuario.requestFocusInWindow();
            return;
        }
        if (cmbICadPerfil.getSelectedIndex()== 0){
            JOptionPane.showMessageDialog(rootPane,"Favor selecione um Perfil");
            cmbICadPerfil.requestFocusInWindow();
            return;
        }
        if (txtICadNome.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Favor inserir um Nome");
            txtICadNome.requestFocusInWindow();
            return;
        }
        if (txtICadEmail.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Favor inserir um Email");
            txtICadEmail.requestFocusInWindow();
            return;
        }
        if (txtICadUsername.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Favor inserir um Username");
            txtICadUsername.requestFocusInWindow();
            return;
        }
        
        String senha = new String(txtICadSenha.getPassword());
        String confsenha = new String(txtICadConfSenha.getPassword());
        
        if (senha.equals("")){
            JOptionPane.showMessageDialog(rootPane,"Favor inserir uma Senha");
            txtICadSenha.requestFocusInWindow();
            return;
        }
        if (confsenha.equals("")){
            JOptionPane.showMessageDialog(rootPane,"Favor inserir uma Confirmação de Senha");
            txtICadConfSenha.requestFocusInWindow();
            return;
        }
        
        if(!senha.equals(confsenha)){
            JOptionPane.showMessageDialog(rootPane,"A sua senha está diferente");
            txtICadSenha.setText("");
            txtICadConfSenha.setText("");
            txtICadSenha.requestFocusInWindow();
            return;
        }
        int pos = msDados.posicaoUsuario(txtICadIdUsuario.getText());
        if(novo){
            if(pos!=-1){
                JOptionPane.showMessageDialog(rootPane,"Este Usuario Ja Existe");
                txtICadIdUsuario.requestFocusInWindow();
                return;
            }
            }else{
                if(pos == -1){
                    JOptionPane.showMessageDialog(rootPane,"Este Usuario Ainda Não Existe");
                    txtICadIdUsuario.requestFocusInWindow();
                    return;
                }
            }
        
        
        Usuario mUsuario = new Usuario(txtICadIdUsuario.getText(), txtICadNome.getText(), txtICadEmail.getText(), txtICadUsername.getText(), senha, cmbICadPerfil.getSelectedIndex());
        String msg;
        if(novo){
            msg = msDados.adicionarUsuario(mUsuario);
        }else{
            msg = msDados.editarUsuario(mUsuario, pos);
        }
        JOptionPane.showMessageDialog(rootPane, msg);
        
        btnICadCriar.setEnabled(true);
        btnICadCons.setEnabled(true);
        btnICadAlterar.setEnabled(true);
        btnICadExcluir.setEnabled(true);
        btnICadSalvar.setEnabled(false);
        btnICadCancelar.setEnabled(false);
        cmbICadPerfil.setEnabled(false);
        btnProsseguir.setEnabled(true);
        btnRetornar.setEnabled(true);
        //Caixa de texto
        txtICadIdUsuario.setEnabled(false);
        txtICadNome.setEnabled(false);
        txtICadEmail.setEnabled(false);
        txtICadUsername.setEnabled(false);
        txtICadSenha.setEnabled(false);
        txtICadConfSenha.setEnabled(false);
        
        preencherTabela();
    }//GEN-LAST:event_btnICadSalvarActionPerformed

    private void btnICadCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnICadCancelarActionPerformed
        btnICadCriar.setEnabled(true);
        btnICadCons.setEnabled(true);
        btnICadAlterar.setEnabled(true);
        btnICadExcluir.setEnabled(true);
        btnICadSalvar.setEnabled(false);
        btnICadCancelar.setEnabled(false);
        cmbICadPerfil.setEnabled(false);
        btnProsseguir.setEnabled(true);
        btnRetornar.setEnabled(true);
        //Caixa de texto
        txtICadIdUsuario.setEnabled(false);
        txtICadNome.setEnabled(false);
        txtICadEmail.setEnabled(false);
        txtICadUsername.setEnabled(false);
        txtICadSenha.setEnabled(false);
        txtICadConfSenha.setEnabled(false);
        //limpar caixas de texto
        txtICadIdUsuario.setText("");
        txtICadNome.setText("");
        txtICadEmail.setText("");
        txtICadUsername.setText("");
        txtICadSenha.setText("");
        txtICadConfSenha.setText("");
        cmbICadPerfil.setSelectedIndex(0);
    }//GEN-LAST:event_btnICadCancelarActionPerformed

    private void btnICadAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnICadAlterarActionPerformed
        btnICadCriar.setEnabled(false);
        btnICadSalvar.setEnabled(true);
        btnICadCancelar.setEnabled(true);
        btnICadCons.setEnabled(false);
        btnICadAlterar.setEnabled(false);
        btnICadExcluir.setEnabled(false);
        cmbICadPerfil.setEnabled(true);
        btnProsseguir.setEnabled(false);
        btnRetornar.setEnabled(false);
        //Caixa de texto
        txtICadNome.setEnabled(true);
        txtICadEmail.setEnabled(true);
        txtICadUsername.setEnabled(true);
        txtICadSenha.setEnabled(true);
        txtICadConfSenha.setEnabled(true);
        novo = false;
        txtICadNome.requestFocus();
    }//GEN-LAST:event_btnICadAlterarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        mostrarRegistro();
        preencherTabela();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarActionPerformed
        usuAtual--;
        if (usuAtual == -1){
            usuAtual = msDados.numeroUsuarios();
        }
        mostrarRegistro();
    }//GEN-LAST:event_btnRetornarActionPerformed

    private void btnProsseguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsseguirActionPerformed
        usuAtual++;
        if (usuAtual == msDados.numeroUsuarios()){
            usuAtual = 0;
        }
        mostrarRegistro();
    }//GEN-LAST:event_btnProsseguirActionPerformed

    private void btnICadExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnICadExcluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja deletar o cadastro?");
        if(resposta !=0){
            return;            
        }
        String msg;
        msg = msDados.deletarUsuario(usuAtual);
        JOptionPane.showMessageDialog(rootPane, msg);
        usuAtual=0;
        mostrarRegistro();
        preencherTabela();
    }//GEN-LAST:event_btnICadExcluirActionPerformed

    private void btnICadConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnICadConsActionPerformed
        String usuario = JOptionPane.showInputDialog("Favor Inserir Codigo do Usuario");
        if(usuario.equals("")){
            return;
        }
        int pos = msDados.posicaoUsuario(usuario);
        if(pos == -1){
            JOptionPane.showMessageDialog(rootPane,"Este Usuario Não Existe");
            return;
        }
        usuAtual = pos;
        mostrarRegistro();
        
    }//GEN-LAST:event_btnICadConsActionPerformed

    private void mostrarRegistro(){
        txtICadIdUsuario.setText(msDados.getUsuarios()[usuAtual].getId());
        txtICadNome.setText(msDados.getUsuarios()[usuAtual].getNome());
        txtICadEmail.setText(msDados.getUsuarios()[usuAtual].getEmail());
        txtICadUsername.setText(msDados.getUsuarios()[usuAtual].getUsername());
        txtICadSenha.setText(msDados.getUsuarios()[usuAtual].getSenha());
        txtICadConfSenha.setText(msDados.getUsuarios()[usuAtual].getSenha());
        cmbICadPerfil.setSelectedIndex(msDados.getUsuarios()[usuAtual].getPerfil());
    }
    
    private void preencherTabela() {
        String titulos[] = {"ID Usuario","Nome","Email","Perfil"};
        String registro[] = new String[4];
        mTabela = new DefaultTableModel(null,titulos);
        for(int i = 0; i < msDados.numeroUsuarios(); i++){
            registro[0]= msDados.getUsuarios()[i].getId();
            registro[1]= msDados.getUsuarios()[i].getNome();
            registro[2]= msDados.getUsuarios()[i].getEmail();
            registro[3]= perfil(msDados.getUsuarios()[i].getPerfil());
            mTabela.addRow(registro);
        }
        tblTabela.setModel(mTabela);
    }
    
    private String perfil(int idPerfil){
        if(idPerfil == 1){
            return"Administrador";
        }else{
            return"Funcionario";
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnICadAlterar;
    private javax.swing.JButton btnICadCancelar;
    private javax.swing.JButton btnICadCons;
    private javax.swing.JButton btnICadCriar;
    private javax.swing.JButton btnICadExcluir;
    private javax.swing.JButton btnICadSalvar;
    private javax.swing.JButton btnProsseguir;
    private javax.swing.JButton btnRetornar;
    private javax.swing.JComboBox<String> cmbICadPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTabela;
    private javax.swing.JPasswordField txtICadConfSenha;
    private javax.swing.JTextField txtICadEmail;
    private javax.swing.JTextField txtICadIdUsuario;
    private javax.swing.JTextField txtICadNome;
    private javax.swing.JPasswordField txtICadSenha;
    private javax.swing.JTextField txtICadUsername;
    // End of variables declaration//GEN-END:variables
}
