
package ateliedocetentacao.form;

import ateliedocetentacao.form.TelaIFormUsuarios;
import ateliedocetentacao.form.TelaFormLogin;
import ateliedocetentacao.model.Usuario;
import ateliedocetentacao.dao.UsuarioDAO;
import ateliedocetentacao.model.Dados;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;

/**
 *
 * @author 202203206631
 */
public class TelaFormEstoque extends javax.swing.JFrame {
    private Dados msDados;

    public void setDados(Dados msDados) {
        this.msDados = msDados;
    }
    
    public TelaFormEstoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpnDesk = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnOpcoes = new javax.swing.JMenu();
        mnOpcoesUsuarios = new javax.swing.JMenuItem();
        mnOpcoesProdutos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnOpcoesTrocarUsuario = new javax.swing.JMenuItem();
        mnOpcoesTrocarSenha = new javax.swing.JMenuItem();
        mnOpcoesSair = new javax.swing.JMenuItem();
        mnRelatorio = new javax.swing.JMenu();
        mnRelatorioRelatorio = new javax.swing.JMenuItem();
        mnAjuda = new javax.swing.JMenu();
        mnAjudaAjuda = new javax.swing.JMenuItem();
        mnAjudaSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Controle de Estoque (WarpPdv)");
        setResizable(false);

        dpnDesk.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout dpnDeskLayout = new javax.swing.GroupLayout(dpnDesk);
        dpnDesk.setLayout(dpnDeskLayout);
        dpnDeskLayout.setHorizontalGroup(
            dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );
        dpnDeskLayout.setVerticalGroup(
            dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );

        mnOpcoes.setText("Opçoes");

        mnOpcoesUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnOpcoesUsuarios.setText("Usuarios");
        mnOpcoesUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOpcoesUsuariosActionPerformed(evt);
            }
        });
        mnOpcoes.add(mnOpcoesUsuarios);

        mnOpcoesProdutos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnOpcoesProdutos.setText("Produtos");
        mnOpcoesProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOpcoesProdutosActionPerformed(evt);
            }
        });
        mnOpcoes.add(mnOpcoesProdutos);
        mnOpcoes.add(jSeparator1);

        mnOpcoesTrocarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnOpcoesTrocarUsuario.setText("Trocar Usuario");
        mnOpcoes.add(mnOpcoesTrocarUsuario);

        mnOpcoesTrocarSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnOpcoesTrocarSenha.setText("Trocar Senha");
        mnOpcoes.add(mnOpcoesTrocarSenha);

        mnOpcoesSair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnOpcoesSair.setText("Sair");
        mnOpcoesSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOpcoesSairActionPerformed(evt);
            }
        });
        mnOpcoes.add(mnOpcoesSair);

        jMenuBar1.add(mnOpcoes);

        mnRelatorio.setText("Relatorios");

        mnRelatorioRelatorio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnRelatorioRelatorio.setText("Relatorio");
        mnRelatorio.add(mnRelatorioRelatorio);

        jMenuBar1.add(mnRelatorio);

        mnAjuda.setText("Ajuda");

        mnAjudaAjuda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnAjudaAjuda.setText("Ajuda");
        mnAjuda.add(mnAjudaAjuda);

        mnAjudaSobre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnAjudaSobre.setText("Sobre");
        mnAjuda.add(mnAjudaSobre);

        jMenuBar1.add(mnAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnDesk)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnDesk)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnOpcoesUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOpcoesUsuariosActionPerformed
        TelaIFormUsuarios mUsuarios = new TelaIFormUsuarios();
        mUsuarios.setDados(msDados);
        dpnDesk.add(mUsuarios);
        mUsuarios.show();
    }//GEN-LAST:event_mnOpcoesUsuariosActionPerformed

    private void mnOpcoesProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOpcoesProdutosActionPerformed
        TelaIFormProdutos msProdutos = new TelaIFormProdutos();
        msProdutos.setDados(msDados);
        dpnDesk.add(msProdutos);
        msProdutos.show();
    }//GEN-LAST:event_mnOpcoesProdutosActionPerformed

    private void mnOpcoesSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOpcoesSairActionPerformed
        msDados.salvarTodo();
        System.exit(0);
    }//GEN-LAST:event_mnOpcoesSairActionPerformed

    /**
     * @param args the   command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFormEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFormEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFormEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFormEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFormEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpnDesk;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mnAjuda;
    private javax.swing.JMenuItem mnAjudaAjuda;
    private javax.swing.JMenuItem mnAjudaSobre;
    private javax.swing.JMenu mnOpcoes;
    private javax.swing.JMenuItem mnOpcoesProdutos;
    private javax.swing.JMenuItem mnOpcoesSair;
    private javax.swing.JMenuItem mnOpcoesTrocarSenha;
    private javax.swing.JMenuItem mnOpcoesTrocarUsuario;
    private javax.swing.JMenuItem mnOpcoesUsuarios;
    private javax.swing.JMenu mnRelatorio;
    private javax.swing.JMenuItem mnRelatorioRelatorio;
    // End of variables declaration//GEN-END:variables
}
